export const languages = [
  { name: "Amharic", code: "am" },
  { name: "Arabic", code: "ar" },
  { name: "Azerbaijani", code: "az" },
  { name: "Bengali", code: "bn" },
  { name: "Bhojpuri", code: "bh" },
  { name: "Burmese", code: "my" },
  { name: "Cantonese (Yue Chinese)", code: "zh" },
  { name: "English", code: "en" },
  { name: "Farsi (Persian)", code: "fa" },
  { name: "Fula", code: "ff" },
  { name: "French", code: "fr" },
  { name: "German", code: "de" },
  { name: "Gujarati", code: "gu" },
  { name: "Hakka Chinese", code: "zh" },
  { name: "Hausa", code: "ha" },
  { name: "Hindi", code: "hi" },
  { name: "Igbo", code: "ig" },
  { name: "Indonesian (Malay)", code: "ms" },
  { name: "Italian", code: "it" },
  { name: "Japanese", code: "ja" },
  { name: "Javanese", code: "jv" },
  { name: "Jin Chinese", code: "zh" },
  { name: "Kannada", code: "kn" },
  { name: "Korean", code: "ko" },
  { name: "Malayalam", code: "ml" },
  { name: "Mandarin Chinese", code: "zh" },
  { name: "Marathi", code: "mr" },
  { name: "Maithili", code: "mai" },
  { name: "Odia (Oriya)", code: "or" },
  { name: "Oromo", code: "om" },
  { name: "Pashto", code: "ps" },
  { name: "Polish", code: "pl" },
  { name: "Portuguese", code: "pt" },
  { name: "Punjabi", code: "pa" },
  { name: "Romanian", code: "ro" },
  { name: "Russian", code: "ru" },
  { name: "Sindhi", code: "sd" },
  { name: "Spanish", code: "es" },
  { name: "Sundanese", code: "su" },
  { name: "Tagalog (Filipino)", code: "tl" },
  { name: "Tamil", code: "ta" },
  { name: "Telugu", code: "te" },
  { name: "Thai", code: "th" },
  { name: "Turkish", code: "tr" },
  { name: "Ukrainian", code: "uk" },
  { name: "Urdu", code: "ur" },
  { name: "Uzbek", code: "uz" },
  { name: "Vietnamese", code: "vi" },
  { name: "Wu Chinese", code: "zh" },
  { name: "Xiang Chinese", code: "zh" },
  { name: "Yoruba", code: "yo" }
];
